### ISSUE TITLE
Not Working with Emuhawk

### ISSUE THREAD

**Issue by Wita5237** [SM64-TAS-ABC/STROOP#107]
When i open up Stroop and select the Emuhawk emulator, STROOP does not get any signal from Emuhawk, Mario in STROOP just sits in front of Peach's castle. Emuhawk version is 2.9.1 and STROOP version is 0.3.0. I still get the RNG updated though. I'm using windows 11 though, is that the problem? It's also the American version of SM64.

**Comment by danebou** [comment]
Try the current dev release. I just added "autodetect" so that should fix it.
