### ISSUE TITLE
Is there any way to get mupen64 rr 0.5?

### ISSUE THREAD

**Issue by TheJoetube** [SM64-TAS-ABC/STROOP#108]
I've searched for 3 hours to find a download for mupen64 rr 0.5 but I could not find a single one, does anyone have a download for it?

**Comment by onlymx13** [comment]
You should be using the new Mupen repack at http://repack.skazzy3.com/. There is no good reason to want to use Mupen 0.5 as it is outdated, has vulnerabilities, and anything created in it works in new Mupen. Hope this helps!

**Comment by TheJoetube** [comment]
> You should be using the new Mupen repack at http://repack.skazzy3.com/. There is no good reason to want to use Mupen 0.5 as it is outdated, has vulnerabilities, and anything created in it works in new Mupen. Hope this helps!

alright, thanks! I thought I had to use the old mupen since the documentation said so

**Comment by Deldee** [comment]
This is a known issue with the ramstart

go to the stroop folder -> config -> config.xml
in mupen, go to help/utilities (depending on your mupen version) -> ram start, click yes to copy
in config.xml, paste it in, overwriting the previous Ramstart mupen value (There will be a line in the file that says "If you are using new Mupen, update the following entry.")

save and then restart stroop and the all the data should be present

**Comment by TheJoetube** [comment]
> This is a known issue with the ramstart
> 
> go to the stroop folder -> config -> config.xml in mupen, go to help/utilities (depending on your mupen version) -> ram start, click yes to copy in config.xml, paste it in, overwriting the previous Ramstart mupen value (There will be a line in the file that says "If you are using new Mupen, update the following entry.")
> 
> save and then restart stroop and the all the data should be present

Alright, thanks
