### ISSUE TITLE
I can't even open STROOP

### ISSUE THREAD

**Issue by SM64TAS** [SM64-TAS-ABC/STROOP#25]
The readme says that I should open the STROOP.exe file, however i looked it up, i checked it like 5 times and there is no STROOP.exe. where can i get the file?

**Comment by danebou** [comment]
> The latest release of Stroop can be downloaded from our Releases Page. From here .zip files of recent builds can be found. The files can then be extracted and Stroop.exe can be opened.

**Comment by danebou** [comment]
You aren't downloading the source code are you?

**Comment by danebou** [comment]
You aren't downloading the source code are you?

**Comment by SM64TAS** [comment]
i came to the conclusion that im retarded. i read the readme after i downloaded it and there was nothing highlighted because i used word. works now, im just an idiot.

**Comment by irishmapping** [comment]
you aren't a retard, you're either normal or blind...
Possibly retarded but it doesn't matter
