### ISSUE TITLE
Hacks tab is broken for me

### ISSUE THREAD

**Issue by onlymx13** [SM64-TAS-ABC/STROOP#33]
The hacks tab doesn't work for me.

**Comment by irishmapping** [comment]
personally, I would have given more information.

**Comment by onlymx13** [comment]
Like what? I remember pannen confirming it didn’t work for anyone

**Comment by danebou** [comment]
I believe this was fixed in the latest version, but I'm yet to retest it.

**Comment by irishmapping** [comment]
> Like what? I remember pannen confirming it didn’t work for anyone

Like, say what happens, maybe technical details, what emu you are using things like that.

**Comment by onlymx13** [comment]
Still doesn’t work on latest STROOP, at least for me.

**Comment by danebou** [comment]
Are you using the latest Dev version? What n64 emulator are you using? Did you remember to turn on pure interpreter mode?

**Comment by onlymx13** [comment]
I’m at school right now so I can’t test the latest version, but this was happening with mupen64-rr pure interpreter mode. Does it work for you?

**Comment by danebou** [comment]
It probably doesn't havent tested it yet.

**Comment by irishmapping** [comment]
well since I'm finally able to use the thing (even though it's at 1 fps);
The hacks tab is very... how do i explain this... *volatile?* Thats the best word I have. For me, it works sometimes but other times doesn't. Which version of SM64 are you using?

**Comment by onlymx13** [comment]
U

**Comment by irishmapping** [comment]
Okay, well, I'm using PAL so that might be some version difference thing?
I'll grab an american copy if I can.

**Comment by onlymx13** [comment]
I’ll try to check tonight.

**Comment by irishmapping** [comment]
k

**Comment by onlymx13** [comment]
Still doesn’t work for me

**Comment by irishmapping** [comment]
I assume you're using win10, yes?

**Comment by onlymx13** [comment]
Yes

**Comment by irishmapping** [comment]
ok then idk, might be a computer issue

**Comment by danebou** [comment]
Fixed in latest dev release
