### ISSUE TITLE
Not working on Bizhawk for macOS

### ISSUE THREAD

**Issue by irishmapping** [SM64-TAS-ABC/STROOP#40]
It doesn't seem to work at all on my iMac Pro running macOS Mojave, however when i switch to Windows 10 on it, it works. It just simply doesn't want to work with Biz. I'm not sure if this is specifically a problem on my computer, but it would be nice to check to make sure it would work. I've tried using Mupen but i don't have a compatible controller for Mupen. If this isn't a problem with the project, sorry for wasting your time, but thanks either way!

**Comment by Siiiimon** [comment]
which version of bizhawk are you using? How are you running BizHawk (Mono/Wine/etc.)?
Maybe I will be able to recreate this problem

**Comment by irishmapping** [comment]
Latest version, Mono.

**Comment by irishmapping** [comment]
Update: I partially fixed the problem. By porting the .exe file to a .app file using more efficient methods, it seems to work _much_ better. However, even the most efficient method will not work. I’ve tried using windows and BizHawk works, but my windows computer is 12 years old and is really bad. Thanks!
