### ISSUE TITLE
Can’t connect to mupen?

### ISSUE THREAD

**Issue by irishmapping** [SM64-TAS-ABC/STROOP#42]
Before i say anything else: I’m not very good with windows, so please be gentle.

I tried opening stroop, but it wouldn’t work with mupen? I tried running it through an automated command, manually, and using cmd.exe. But it won’t work. I have tried everything i can think of. 

Sorry if i’m wasting your time, it’s probably because i’m an idiot with using windows ¯\_(ツ)_/¯

**Comment by irishmapping** [comment]
okay i partially fixed the issue by being less of a retard, it can connect now but won't really do anything

**Comment by danebou** [comment]
what version of mupen are you using? Also what version of the game? (US/JP?)

**Comment by irishmapping** [comment]
The latest stable release (2.5), and I am using the Shindou Pack, do I need to use the original JP? And, can I not use PAL either?

**Comment by danebou** [comment]
> Marios must be American, Japanese or PAL

Yeah Shindou is not supported

**Comment by onlymx13** [comment]
Although Pannen has expressed intent to add it in the future

**Comment by irishmapping** [comment]
Okay, so... I will have to use my PAL cartridge that I haven't gotten the rom onto my computer. I'll try that.
And I have trouble using mupen 0.5 so can I have some help with that maybe?

**Comment by danebou** [comment]
What trouble are you having with 0.5? use this download link (one in the description): http://adelikat.tasvideos.org/emulatordownloads/mupen64-rr/Mupen64%20v8%20installer.zip

**Comment by irishmapping** [comment]
I have trouble with:
1. Opening it
2. Getting it to run games
3. Running using cmd.exe

**Comment by irishmapping** [comment]
After about 3 days of me not being tarded (for once, pretty rare) i managed to get my PAL cartridge onto my computer. Since i cant figure out 0.5, i had to use 2.5 and customised the base address. But, it's really, *really* slow, which normally it isn't... Something to keep in mind is my computer is a 2 year old HP spectre x360, and it doesn't run games well but normally it works fine. Is it a problem with not supporting HP's BIOS or something?

**Comment by irishmapping** [comment]
> Although Pannen has expressed intent to add it in the future

Well, I really hope he does, because the Shindou version happens to be the most stable with my own experience. Plus, it's the only one I have that can run on my old-ass japanese n64 (that my cousin used to own) for some reason, which is why it's the only one I can really use (except for the PAL cartridge I stole from my sister)

**Comment by danebou** [comment]
What version of windows are you using?

**Comment by danebou** [comment]
I just ran it with cmd no issue

**Comment by danebou** [comment]
(no command line args)

**Comment by irishmapping** [comment]
Windows 8.

**Comment by onlymx13** [comment]
8 or 8,1?

**Comment by irishmapping** [comment]
just 8

**Comment by onlymx13** [comment]
.NET 4.7.1 can’t be installed on pure Windows 8.

**Comment by irishmapping** [comment]
Can it be on 8.1?

**Comment by onlymx13** [comment]
Yes

**Comment by danebou** [comment]
Win 8 is not supported, but Win 8.1 is

**Comment by irishmapping** [comment]
Okay. This is just really what I whould have done long ago because windows 8 is bad and I never updated it because I didn't feel like it.

**Comment by irishmapping** [comment]
ok

> STROOP doesn't support Win 8, but does support Win 8.1

k

**Comment by onlymx13** [comment]
There’s no need to avoid Windows 10 either, just sayin’

**Comment by danebou** [comment]
Although I believe @onlymx13 just made a PR for win8 support

**Comment by irishmapping** [comment]
Meh, I've seen Windows 10 and it looks bad. I honestly use windows 8 because it's pretty easy to use (atleast for me)


> Although I believe @onlymx13 just made a PR for win8 support

Okay 2: electric boogaloo
anyway see you in three years when I actually find a windows 8.1 installation disk!

**Comment by onlymx13** [comment]
It wasn’t me, and Windows 8 is absolutely horrifying compared to Windows 10. You won’t lose anything.

**Comment by danebou** [comment]
I'm surprised mupen 0.5 isn't working for you. You're launching the exe right?

**Comment by irishmapping** [comment]
Well, I will update to windows 10 soon, from what I know HP will be removing support for windows 8 on the computer I have but idk. and I have to update to 8.1 first before 10 because if i go 8 to 10, ill lose my data.


> I'm surprised mupen 0.5 isn't working for you. You're launching the exe right?

I'm launching it using cmd.exe because the exe itself didnt work

**Comment by danebou** [comment]
What do you mean by it didn't work. When you click it what happens? (So far I'm just blaming this on Win8)

**Comment by irishmapping** [comment]
it either launches it but immediately closes and gives me an error in the console, or doesnt even open or give an error.

**Comment by danebou** [comment]
What error?

**Comment by irishmapping** [comment]
"Can not open 'mupen0.5' (i renamed it to that btw), application may be unsupported."

**Comment by irishmapping** [comment]
Weird thing is, I didn't even know that error existed

**Comment by onlymx13** [comment]
Maybe Mupen doesn’t support win8

**Comment by irishmapping** [comment]
Possibly. I'll update to 8.1 and if that doesnt work then 10. (after 3 years of finding an actual win8.1 disk)

**Comment by mat1jaczyyy** [comment]
#48 should bring Windows 8 support. You can try compile my fork and see if it works for you. I am able to run STROOP with the changes and fully utilize it. I've used it for TAS comps earlier, just forgot to make a pull. 

I'm using the earliest release build of W10, and attempting to run STROOP binaries from GitHub Releases does not work at all, citing a 4.7 requirement that I'm unable to satisfy.

**Comment by irishmapping** [comment]
ok

**Comment by danebou** [comment]
All PRs are built on the server. Go download it here: https://dev.azure.com/SM64-TASing-ABC/STROOP/_build/results?buildId=68 

(Artifacts -> drop)

**Comment by irishmapping** [comment]
okay, ill try thay

**Comment by irishmapping** [comment]
I accidentally woke up late oof. Anyway it seems to work moetly fine now but the remaining troubles is just HP having horrible BIOS setups and shit like that, thank you very much @mat1jaczyyy !

**Comment by irishmapping** [comment]
wait wtf HP stop destroying the BIOS its already bad enough heeeeeeeeeeeeeeelp stop now if you dont stop I will start using dell aaaaa
In all seriousness the HP bios is so bad its kind of funny
