### ISSUE TITLE
Zooming in in Map2 eventually stretches the map sideways and crops the map.

### ISSUE THREAD

**Issue by jongyon7192p** [SM64-TAS-ABC/STROOP#65]
I dunno how to use github and i dunno what this Issues thing is, but im thinking maybe it has to do with the Math.Min function? I have no clue what else could cause this asymmetry between width and height.

Also, minor issue, if you zoom way far enough, when you zoom back in, it won't. it just... i dunno, it does nothing, i think?

**Comment by danebou** [comment]
The button zoom? Also map2 is gone now. And although this now happens with the scale controller, let's call it a feature lol.
