### ISSUE TITLE
Model tab camera zooms even if you click out into another window AND EVEN if you're in another STROOP tab!!.

### ISSUE THREAD

**Issue by jongyon7192p** [SM64-TAS-ABC/STROOP#67]
man, i'm just not using the model tab sometimes, man. Lemme use my scroll wheel w/o fucking up the model tab.

You'll notice the change once you click the model viewing box/square/thingy. Is that what's called a viewport? I dunno. But yknow what im referring to.

**Comment by danebou** [comment]
Fixed
