### ISSUE TITLE
Support mupen64plus as an emulator

### ISSUE THREAD

**Issue by norbjd** [SM64-TAS-ABC/STROOP#73]
Hello :wave:,

The `STROOP/Config/Config.xml` file defines the following emulators :

```
<Emulators>
    <Emulator name="Mupen 5.0 RR" processName="mupen64-rerecording" ramStart="0x008EBA80" endianness="little"/>
    <Emulator name="Mupen 5.0 RR" processName="mupen64-pucrash" ramStart="0x00912300" endianness="little"/>
    <Emulator name="Mupen 5.0 RR" processName="mupen64_lua" ramStart="0x00888F60" endianness="little"/>
    <Emulator name="Mupen 5.0 RR" processName="mupen64-wiivc" ramStart="0x00901920" endianness="little"/>
    <Emulator name="Mupen 5.0 RR" processName="mupen64-RTZ" ramStart="0x00901920" endianness="little"/>
    <Emulator name="Mupen 5.0 RR" processName="mupen64-rerecording-v2-reset" ramStart="0x008ECA90" endianness="little"/>
    <Emulator name="Mupen 5.0 RR" processName="mupen64-rrv8-avisplit" ramStart="0x008ECBB0" endianness="little"/>

    <Emulator name="Nemu64 0.8" processName="Nemu64" ramStart="0x10020000" endianness="little"/>
    <Emulator name="BizHawk" processName="EmuHawk" offsetDll="mupen64plus.dll" ramStart="0x6A1C0" endianness="little"/>
    <Emulator name="Project64 Debugger 2.4.0.9999" processName="Project64d" ramStart="0x20000000" endianness="little"/>
    <Emulator name="Project64" processName="Project64" ramStart="0x4BAF0000" endianness="little"/>
    <Emulator name="Dolphin" processName="Dolphin" ramStart="0xe6a180" endianness="big" special="dolphin"/>
</Emulators>
```

Would it be possible to add `mupen64plus` (https://mupen64plus.org/)?

This will be useful for issue #72 for example, but also mostly for people using Mupen64Plus. I'm wondering, how did you find `ramStart` for other emulators? I'll try to notify everyone who made a modification on this file (`git blame`) :smile: : @scob @danebou @dkorpel @Thestickman391 @1ted59.

Thank you very much.

**Comment by onlymx13** [comment]
Maybe try using Cheat Engine to find the value of the coin count on a certain game version and put that here. That could be convertible into a RAM start value.

**Comment by norbjd** [comment]
As I thought, Cheat Engine was not available on GNU/Linux :laughing:. But, with `scanmem` (https://linux.die.net/man/1/scanmem) and `gameconqueror` (https://framalibre.org/content/gameconqueror), I was able to scan the memory used by a process for changes. From one execution of the other of mupen, the memory address inside the process changes (like `7f38d335335a` or `7f38d33533a0`), but the offset of coin count remains the same. I found 2 offsets :

- c3a35a
- c3a3a0

I think `c3a3a0` corresponds to the display of coin count , and `c3a35a` corresponds to the **real coin count**.

If I follow this memory address map (https://sites.google.com/site/sm64gameshark/resources/memory-addresses), the coin count for US version is located at the address 8033B218.

Is that necessary to find `ramStart`?

**Comment by norbjd** [comment]
Hmm, in STROOP file `Config/HudData.xml`, I found this :

https://github.com/SM64-TAS-ABC/STROOP/blob/7ecacf40833f226ee8f180fde7653243301cc5c4/STROOP/Config/HudData.xml#L12-L14

Maybe that could also help.

**Comment by norbjd** [comment]
With the help of @onlymx13, we found that the actual address of coin count in N64 for US version is `0x8033B218`.
I've found that the coin count offset for `mupen64plus` (US version of the game) is `0xC3A35A`. So, if I didn't made any mistake when finding the coin offset, we can do the difference between the 2 values :

`abs(0x8033B218 - 0x80C3A35A) = 0x008FF142‬`

and found that `ramStart` for `mupen64plus` should be `0x008FF142‬`.

I've not tested it because I don't have a Windows machine and as for now, I cannot connect to a running emulator on GNU/Linux.
I'll make a PR soon to add `mupen64plus` emulator available, hoping that it will work connecting.

**Comment by Aurumaker72** [comment]
Ok but ram start will change with any new thing added

**Comment by Wita5237** [comment]
I heard that the file can be edited directly. Why not we just ask each of the developers and get the new values?

**Comment by norbjd** [comment]
I'm going to close the issue as it's been nearly 4 years and things might have changed since then :sweat_smile:

**Comment by danebou** [comment]
It might actually be fixed now. Set autoDetect to true in the config file like the other emulators. Let me know if that fixes it.
