### ISSUE TITLE
STROOP and project64

### ISSUE THREAD

**Issue by isaacmakessoftware** [SM64-TAS-ABC/STROOP#86]
I am having issues with project64, when I try to use it with STROOP, it shows up in the list to connect to but when connected nothing shows up in the program. In the config file project64 is specified however it does not work. Nemu does work and shows fine however project64 is my preferred emulator so how can I make it work? I am using project64 2.3

**Comment by ethpsa09** [comment]
this also happens to me
the variables just show up as blank not even (none)

**Comment by danebou** [comment]
Yeah can confirm. Project64 has its memory layout differently. Not sure when this will be fixed on the roadmap.

**Comment by danebou** [comment]
It's as simple as project64 doesn't use expanded ram size by default, so it wasn't reading memory properly. I fixed it now by automatically overriding the expanded ram size function if the memory can't be read.
