### ISSUE TITLE
Update the mupen64 link.

### ISSUE THREAD

**Issue by ibisrecordings** [SM64-TAS-ABC/STROOP#92]
It doesn't work anymore. 
[https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mupen64-rr/Mupen64%20v8%20installer.zip](https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mupen64-rr/Mupen64%20v8%20installer.zip)
Here is an archive of the original

**Comment by danebou** [comment]
Removed the link. Most mupens should be supported by now
