### ISSUE TITLE
M64 editor uses incorrect max value when setting VI count to max

### ISSUE THREAD

**Issue by 1ted59** [SM64-TAS-ABC/STROOP#94]
The first few M64 fields are unsigned 32 bit numbers, equivalent to `uint` in C#. STROOP incorrectly uses signed `int` fields for those, meaning large values aren't handled correctly. This normally wouldn't affect much (as m64's that big are pretty absurd), except for the `Max Out VI Count` setting the value to `int.MaxValue`.

The fields `NumInputs`, `NumVis`, and `NumRerecords`  should be changed to `uint` instead, and Max Out VI Count should set the value to `uint.MaxValue` instead, for the true max VI value.

This makes mupen correctly display the count as -1, for what its worth.

**Comment by 1ted59** [comment]
Unrelated, but I would probably recommend changing that check box to off when New Mupen 1.1.0 is released, as the bug where VI's would make a movie stop early is [currently fixed on the dev branch](https://github.com/mkdasher/mupen64-rr-lua-/pull/55).

**Comment by danebou** [comment]
Done. I don't know about the checkbox though, since I don't if everyone moved to mupen1.1.0 yet.
