### ISSUE TITLE
STROOP not detecting Project64

### ISSUE THREAD

**Issue by Bandu42794** [SM64-TAS-ABC/STROOP#97]
I use Project64 as my main emulator, but when I load STROOP on PJ64, there is nothing. Everything is blank. So I have to use mupen64-rerecording (yes I use that).

**Comment by kinderhead** [comment]
I don't think PJ64 is supported by STROOP. It's just mupen64-rr and BizHawk

**Comment by danebou** [comment]
Yeah its broken right now. Duplicate of #86
