### ISSUE TITLE
this is all i see when i launch stroop. pls fix i love stroop

### ISSUE THREAD

**Issue by yoyeet961** [SM64-TAS-ABC/STROOP#99]
![image](https://github.com/SM64-TAS-ABC/STROOP/assets/85292886/bcf8d06e-4178-4bc2-911e-6c406766e58a)

**Comment by Aurumaker72** [comment]
https://github.com/SM64-TAS-ABC/STROOP/issues/84

**Comment by danebou** [comment]
Duplicate. Will respond to the first issue.
